import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { WORKFLOWS } from "./workflows.js";

export const SUPPORTED_TOOLS = ["claude", "codex"] as const;
export type ToolId = (typeof SUPPORTED_TOOLS)[number];

export interface GeneratedFile {
  path: string;
  skipped: boolean;
}

const banner = (version: string): string =>
  `<!-- generated by skillet ${version} — do not edit; regenerate with 'skillet init --force' -->`;

/**
 * Claude Code: project-local slash commands under
 * `.claude/commands/skillet/<id>.md`, invoked as /skillet:<id>.
 */
const generateClaude = (projectRoot: string, version: string, force: boolean): GeneratedFile[] => {
  const dir = join(projectRoot, ".claude", "commands", "skillet");
  mkdirSync(dir, { recursive: true });
  return WORKFLOWS.map((wf) => {
    const path = join(dir, `${wf.id}.md`);
    if (existsSync(path) && !force) return { path, skipped: true };
    const content = `---\ndescription: ${wf.description}\n---\n\n${banner(version)}\n\n${wf.body}\n`;
    writeFileSync(path, content);
    return { path, skipped: false };
  });
};

/**
 * Codex CLI: global prompts under `$CODEX_HOME/prompts/skillet-<id>.md`
 * (codex has no project-local prompt directory), invoked as
 * /skillet-<id>.
 */
const generateCodex = (version: string, force: boolean): GeneratedFile[] => {
  const codexHome = process.env["CODEX_HOME"] ?? join(homedir(), ".codex");
  const dir = join(codexHome, "prompts");
  mkdirSync(dir, { recursive: true });
  return WORKFLOWS.map((wf) => {
    const path = join(dir, `skillet-${wf.id}.md`);
    if (existsSync(path) && !force) return { path, skipped: true };
    writeFileSync(path, `${banner(version)}\n\n${wf.body}\n`);
    return { path, skipped: false };
  });
};

export const generateTool = (
  tool: ToolId,
  projectRoot: string,
  version: string,
  force: boolean,
): GeneratedFile[] => {
  return tool === "claude"
    ? generateClaude(projectRoot, version, force)
    : generateCodex(version, force);
};
